/**
 * Synthetic FedEx Ground invoice with planted billing errors.
 *
 * Every package is generated by a seeded formula. Destinations are drawn from
 * the public Census ZIP3 geography used by the zone optimizer, zones come from
 * the same ZIP3 distance model, and transportation charges come from the
 * site's synthetic rate table, which sits at roughly half of list. Surcharge
 * amounts are the published 2026 FedEx figures in rules.ts.
 *
 * The planted errors are the answer key. The agent never sees this file's
 * `planted` list; it sees the invoice and the rules, and the page scores what
 * it found against what was planted.
 */
import { getBaseRate } from "@/lib/rates";
import { getZone, listZip3 } from "@/lib/zones";
import { mulberry32 } from "@/lib/labs/zone-optimizer/orders";
import {
  amounts,
  type RuleId,
  type Zone,
  zoneTier,
  DIM_DIVISOR,
  AHS_DIMENSION_MIN_BILLABLE_LB,
  OVERSIZE_MIN_BILLABLE_LB,
  FUEL_APPLIES_TO,
} from "./rules";

export type Service = "FedEx Ground" | "FedEx Home Delivery";
export type AddressType = "commercial" | "residential";
export type DasTier = "none" | "das" | "extended" | "remote";
export type SignatureOption = "none" | "direct" | "adult";

export type ChargeCode =
  | "TRANSPORTATION"
  | "FUEL"
  | "RESIDENTIAL"
  | "DAS"
  | "DAS_EXTENDED"
  | "DAS_REMOTE"
  | "AHS_DIMENSION"
  | "AHS_WEIGHT"
  | "AHS_PACKAGING"
  | "OVERSIZE"
  | "SIGNATURE_DIRECT"
  | "SIGNATURE_ADULT"
  | "ADDRESS_CORRECTION";

export type Charge = { code: ChargeCode; description: string; amount: number };

export type Dims = { l: number; w: number; h: number };

export type InvoicePackage = {
  tracking: string;
  service: Service;
  shipDate: string;
  originZip3: string;
  destZip3: string;
  /** Address type from the shipper's own order record, not from the carrier. */
  destAddressType: AddressType;
  /** DAS tier the carrier billed. The shipper cannot verify the tier without FedEx's ZIP tables. */
  dasTier: DasTier;
  /** Signature option the shipper selected at label creation. */
  signatureRequested: SignatureOption;
  dimsIn: Dims;
  actualLb: number;
  /** Weight the carrier billed against. */
  billedLb: number;
  zone: Zone;
  charges: Charge[];
};

export type Invoice = {
  number: string;
  carrier: "FedEx";
  periodStart: string;
  periodEnd: string;
  /** Fuel percentage stated for the period, as a fraction. */
  fuelPct: number;
  originZip3: string;
  originLabel: string;
  packages: InvoicePackage[];
  total: number;
};

export type PlantedKind =
  | "RESIDENTIAL_ON_COMMERCIAL"
  | "RESIDENTIAL_EXPRESS_RATE"
  | "AHS_NO_TRIGGER"
  | "AHS_WRONG_ZONE_TIER"
  | "BILLED_WEIGHT_INFLATED"
  | "DAS_DUPLICATE"
  | "OVERSIZE_NO_TRIGGER"
  | "FUEL_WRONG_PERCENT";

export type PlantedError = {
  kind: PlantedKind;
  tracking: string;
  /** Charge code the error lives on. */
  code: ChargeCode;
  ruleId: RuleId;
  billed: number;
  expected: number;
  /** Dollars the shipper can claim back on this line. */
  recoverable: number;
  note: string;
};

export type AuditFixture = {
  invoice: Invoice;
  planted: PlantedError[];
};

export const DEFAULT_SEED = 20260925;
export const PACKAGE_COUNT = 40;
export const ORIGIN_ZIP3 = "660";
export const ORIGIN_LABEL = "Kansas City, KS (ZIP3 660)";
const FUEL_PCT = 0.165;
const PERIOD_START = "2026-09-14";
const PERIOD_END = "2026-09-20";

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}

export function dimWeightLb(d: Dims): number {
  const cubic = Math.ceil(d.l) * Math.ceil(d.w) * Math.ceil(d.h);
  return Math.ceil(cubic / DIM_DIVISOR);
}

export function billableLb(d: Dims, actualLb: number): number {
  return Math.max(Math.ceil(actualLb), dimWeightLb(d));
}

function fuelOn(charges: Charge[], fuelPct: number): number {
  const base = charges
    .filter((c) => (FUEL_APPLIES_TO as readonly string[]).includes(c.code))
    .reduce((sum, c) => sum + c.amount, 0);
  return round2(base * fuelPct);
}

const dasAmount: Record<Exclude<DasTier, "none">, (a: AddressType) => number> = {
  das: (a) => (a === "residential" ? amounts.das.residential : amounts.das.commercial),
  extended: (a) =>
    a === "residential" ? amounts.das.extendedResidential : amounts.das.extendedCommercial,
  remote: () => amounts.das.remote,
};

const dasCode: Record<Exclude<DasTier, "none">, ChargeCode> = {
  das: "DAS",
  extended: "DAS_EXTENDED",
  remote: "DAS_REMOTE",
};

/** A typical direct to consumer carton mix. Dims in inches, weight in pounds. */
type Profile = { dims: Dims; actualLb: number };

function drawProfile(random: () => number): Profile {
  const r = random();
  if (r < 0.45) {
    // Small carton, weight wins.
    return {
      dims: { l: 10 + random() * 4, w: 8 + random() * 3, h: 4 + random() * 3 },
      actualLb: 1 + random() * 5,
    };
  }
  if (r < 0.8) {
    // Medium carton, dim weight often wins.
    return {
      dims: { l: 14 + random() * 6, w: 12 + random() * 4, h: 8 + random() * 6 },
      actualLb: 3 + random() * 9,
    };
  }
  if (r < 0.95) {
    // Large carton, dim weight always wins.
    return {
      dims: { l: 22 + random() * 8, w: 16 + random() * 6, h: 12 + random() * 8 },
      actualLb: 8 + random() * 14,
    };
  }
  // Heavy and dense.
  return {
    dims: { l: 16 + random() * 6, w: 12 + random() * 4, h: 10 + random() * 4 },
    actualLb: 30 + random() * 25,
  };
}

function tracking(random: () => number, index: number): string {
  const block = Math.floor(random() * 1e9)
    .toString()
    .padStart(9, "0");
  return `7${String(index + 1).padStart(2, "0")}${block}`;
}

function shipDate(random: () => number): string {
  const day = 14 + Math.floor(random() * 6);
  return `2026-09-${String(day).padStart(2, "0")}`;
}

/**
 * Bill a package correctly from its facts. Used both to build honest lines and
 * as the reference the checks compare against.
 */
export function correctCharges(
  pkg: Omit<InvoicePackage, "charges" | "billedLb"> & { billedLb?: number },
  fuelPct: number,
  /** Bill against this weight instead of the computed one. Used only to plant an error. */
  billedLbOverride?: number,
): { charges: Charge[]; billedLb: number } {
  const charges: Charge[] = [];
  const d = pkg.dimsIn;
  const longest = Math.max(d.l, d.w, d.h);
  const sides = [d.l, d.w, d.h].sort((a, b) => b - a);
  const girth = sides[0] + 2 * sides[1] + 2 * sides[2];
  const cubic = Math.ceil(d.l) * Math.ceil(d.w) * Math.ceil(d.h);

  const ahsDim =
    longest > 48 || sides[1] > 30 || girth > 105 || cubic > 10_368;
  const ahsWeight = pkg.actualLb > 50;
  const oversize =
    longest > 96 || girth > 130 || cubic > 17_280 || pkg.actualLb > 110;

  let billed = billableLb(d, pkg.actualLb);
  if (oversize) billed = Math.max(billed, OVERSIZE_MIN_BILLABLE_LB);
  else if (ahsDim) billed = Math.max(billed, AHS_DIMENSION_MIN_BILLABLE_LB);
  if (billedLbOverride !== undefined) billed = billedLbOverride;

  charges.push({
    code: "TRANSPORTATION",
    description: `${pkg.service}, zone ${pkg.zone}, ${billed} lb`,
    amount: getBaseRate(pkg.zone, billed),
  });

  if (pkg.destAddressType === "residential") {
    charges.push({
      code: "RESIDENTIAL",
      description: "Residential Delivery Charge",
      amount: amounts.residential.ground,
    });
  }
  if (pkg.dasTier !== "none") {
    charges.push({
      code: dasCode[pkg.dasTier],
      description: `Delivery Area Surcharge, ${pkg.dasTier}`,
      amount: dasAmount[pkg.dasTier](pkg.destAddressType),
    });
  }
  const tier = zoneTier(pkg.zone);
  if (oversize) {
    charges.push({ code: "OVERSIZE", description: "Oversize Charge", amount: amounts.oversize[tier] });
  } else {
    if (ahsDim) {
      charges.push({
        code: "AHS_DIMENSION",
        description: "Additional Handling Surcharge, Dimension",
        amount: amounts.ahsDimension[tier],
      });
    }
    if (ahsWeight) {
      charges.push({
        code: "AHS_WEIGHT",
        description: "Additional Handling Surcharge, Weight",
        amount: amounts.ahsWeight[tier],
      });
    }
  }
  if (pkg.signatureRequested === "direct") {
    charges.push({ code: "SIGNATURE_DIRECT", description: "Direct Signature Required", amount: amounts.signature.direct });
  } else if (pkg.signatureRequested === "adult") {
    charges.push({ code: "SIGNATURE_ADULT", description: "Adult Signature Required", amount: amounts.signature.adult });
  }

  charges.splice(1, 0, {
    code: "FUEL",
    description: `Fuel surcharge, ${(fuelPct * 100).toFixed(1)}%`,
    amount: fuelOn(charges, fuelPct),
  });
  return { charges, billedLb: billed };
}

function setCharge(charges: Charge[], code: ChargeCode, amount: number): void {
  const c = charges.find((x) => x.code === code);
  if (c) c.amount = amount;
}

function refuel(charges: Charge[], fuelPct: number): void {
  const fuel = charges.find((c) => c.code === "FUEL");
  if (fuel) fuel.amount = fuelOn(charges, fuelPct);
}

/**
 * Build the invoice and the answer key. Same seed, same invoice.
 */
export function buildFixture(seed: number = DEFAULT_SEED): AuditFixture {
  const random = mulberry32(seed);
  const zips = listZip3().filter((z) => getZone(ORIGIN_ZIP3, z) !== undefined);
  const packages: InvoicePackage[] = [];

  for (let i = 0; i < PACKAGE_COUNT; i += 1) {
    const destZip3 = zips[Math.floor(random() * zips.length)];
    const zone = getZone(ORIGIN_ZIP3, destZip3) as Zone;
    const profile = drawProfile(random);
    const destAddressType: AddressType = random() < 0.8 ? "residential" : "commercial";
    const dasDraw = random();
    const dasTier: DasTier =
      dasDraw < 0.72 ? "none" : dasDraw < 0.9 ? "das" : dasDraw < 0.97 ? "extended" : "remote";
    const sigDraw = random();
    const signatureRequested: SignatureOption =
      sigDraw < 0.88 ? "none" : sigDraw < 0.96 ? "direct" : "adult";

    const base = {
      tracking: tracking(random, i),
      service: destAddressType === "residential" ? ("FedEx Home Delivery" as const) : ("FedEx Ground" as const),
      shipDate: shipDate(random),
      originZip3: ORIGIN_ZIP3,
      destZip3,
      destAddressType,
      dasTier,
      signatureRequested,
      dimsIn: {
        l: round2(profile.dims.l),
        w: round2(profile.dims.w),
        h: round2(profile.dims.h),
      },
      actualLb: round2(profile.actualLb),
      zone,
    };
    const { charges, billedLb } = correctCharges(base, FUEL_PCT);
    packages.push({ ...base, billedLb, charges });
  }

  // Plant the errors on fixed positions so the mix is stable across seeds.
  // Each one edits the carrier's lines, never the shipper's facts.
  const planted: PlantedError[] = [];
  const at = (n: number) => packages[n];

  // 1. Residential charge on a commercial delivery.
  {
    const p = at(3);
    p.destAddressType = "commercial";
    p.service = "FedEx Ground";
    const fixed = correctCharges(p, FUEL_PCT);
    p.charges = fixed.charges;
    p.billedLb = fixed.billedLb;
    p.charges.push({ code: "RESIDENTIAL", description: "Residential Delivery Charge", amount: amounts.residential.ground });
    refuel(p.charges, FUEL_PCT);
    planted.push({
      kind: "RESIDENTIAL_ON_COMMERCIAL",
      tracking: p.tracking,
      code: "RESIDENTIAL",
      ruleId: "RESIDENTIAL",
      billed: amounts.residential.ground,
      expected: 0,
      recoverable: round2(amounts.residential.ground * (1 + FUEL_PCT)),
      note: "Shipper's order record says commercial. The carrier billed the residential charge, and fuel on top of it.",
    });
  }

  // 2. Residential charge at the Express rate on a Home Delivery package.
  {
    const p = at(7);
    p.destAddressType = "residential";
    p.service = "FedEx Home Delivery";
    const fixed = correctCharges(p, FUEL_PCT);
    p.charges = fixed.charges;
    p.billedLb = fixed.billedLb;
    setCharge(p.charges, "RESIDENTIAL", amounts.residential.express);
    refuel(p.charges, FUEL_PCT);
    planted.push({
      kind: "RESIDENTIAL_EXPRESS_RATE",
      tracking: p.tracking,
      code: "RESIDENTIAL",
      ruleId: "RESIDENTIAL",
      billed: amounts.residential.express,
      expected: amounts.residential.ground,
      recoverable: round2((amounts.residential.express - amounts.residential.ground) * (1 + FUEL_PCT)),
      note: "The $6.95 figure is the Express rate. Ground and Home Delivery carry $6.45.",
    });
  }

  // 3. Additional Handling, Dimension, on a package that meets no trigger.
  {
    const p = at(11);
    p.dimsIn = { l: 46, w: 14, h: 10 };
    p.actualLb = 12.4;
    const fixed = correctCharges(p, FUEL_PCT);
    p.charges = fixed.charges;
    p.billedLb = fixed.billedLb;
    const amount = amounts.ahsDimension[zoneTier(p.zone)];
    p.charges.push({ code: "AHS_DIMENSION", description: "Additional Handling Surcharge, Dimension", amount });
    refuel(p.charges, FUEL_PCT);
    planted.push({
      kind: "AHS_NO_TRIGGER",
      tracking: p.tracking,
      code: "AHS_DIMENSION",
      ruleId: "AHS_DIMENSION",
      billed: amount,
      expected: 0,
      recoverable: round2(amount * (1 + FUEL_PCT)),
      note: "Longest side 46 in, second 14 in, length plus girth 94 in, 6,440 cubic in. None of the four triggers is met.",
    });
  }

  // 4. Additional Handling, Dimension, billed at the wrong zone tier.
  {
    const p = at(15);
    p.dimsIn = { l: 52, w: 12, h: 10 };
    p.actualLb = 9;
    // Force a zone 2 destination so the tier is unambiguous.
    const zone2 = zips.find((z) => getZone(ORIGIN_ZIP3, z) === 2);
    if (zone2) {
      p.destZip3 = zone2;
      p.zone = 2;
    }
    const fixed = correctCharges(p, FUEL_PCT);
    p.charges = fixed.charges;
    p.billedLb = fixed.billedLb;
    setCharge(p.charges, "AHS_DIMENSION", amounts.ahsDimension.z3_4);
    refuel(p.charges, FUEL_PCT);
    planted.push({
      kind: "AHS_WRONG_ZONE_TIER",
      tracking: p.tracking,
      code: "AHS_DIMENSION",
      ruleId: "AHS_DIMENSION",
      billed: amounts.ahsDimension.z3_4,
      expected: amounts.ahsDimension.z2,
      recoverable: round2((amounts.ahsDimension.z3_4 - amounts.ahsDimension.z2) * (1 + FUEL_PCT)),
      note: "The surcharge is real; 52 in exceeds the 48 in trigger. The amount is the Zones 3-4 figure on a zone 2 package.",
    });
  }

  // 5. Billed weight inflated past both actual and dimensional weight.
  {
    const p = at(19);
    p.dimsIn = { l: 12, w: 12, h: 12 };
    p.actualLb = 9;
    const fixed = correctCharges(p, FUEL_PCT);
    const correctLb = fixed.billedLb; // 1728 / 139 = 12.43, rounds to 13
    const inflatedLb = correctLb + 5;
    const inflated = correctCharges(p, FUEL_PCT, inflatedLb);
    p.charges = inflated.charges;
    p.billedLb = inflatedLb;
    const billed = inflated.charges[0].amount;
    const expected = fixed.charges[0].amount;
    planted.push({
      kind: "BILLED_WEIGHT_INFLATED",
      tracking: p.tracking,
      code: "TRANSPORTATION",
      ruleId: "DIM_WEIGHT",
      billed,
      expected,
      recoverable: round2((billed - expected) * (1 + FUEL_PCT)),
      note: `Actual 9 lb, dimensional ${correctLb} lb, billed ${inflatedLb} lb. Nothing in the shipper's record supports the billed weight.`,
    });
  }

  // 6. Delivery Area Surcharge billed twice on one package.
  {
    const p = at(23);
    p.dasTier = "das";
    const fixed = correctCharges(p, FUEL_PCT);
    p.charges = fixed.charges;
    p.billedLb = fixed.billedLb;
    const amount = dasAmount.das(p.destAddressType);
    p.charges.push({ code: "DAS", description: "Delivery Area Surcharge", amount });
    refuel(p.charges, FUEL_PCT);
    planted.push({
      kind: "DAS_DUPLICATE",
      tracking: p.tracking,
      code: "DAS",
      ruleId: "DAS",
      billed: amount * 2,
      expected: amount,
      recoverable: round2(amount * (1 + FUEL_PCT)),
      note: "Two DAS lines on one package. The surcharge is per package, once.",
    });
  }

  // 7. Oversize Charge on a package that only meets the Additional Handling trigger.
  {
    const p = at(27);
    p.dimsIn = { l: 60, w: 18, h: 16 }; // longest 60, L+G 128, cubic 17,280 exactly (not greater)
    p.actualLb = 22;
    const fixed = correctCharges(p, FUEL_PCT);
    p.charges = fixed.charges;
    p.billedLb = fixed.billedLb;
    const ahs = p.charges.find((c) => c.code === "AHS_DIMENSION");
    const tier = zoneTier(p.zone);
    if (ahs) {
      ahs.code = "OVERSIZE";
      ahs.description = "Oversize Charge";
      ahs.amount = amounts.oversize[tier];
    }
    refuel(p.charges, FUEL_PCT);
    planted.push({
      kind: "OVERSIZE_NO_TRIGGER",
      tracking: p.tracking,
      code: "OVERSIZE",
      ruleId: "OVERSIZE",
      billed: amounts.oversize[tier],
      expected: 0,
      // Net of the Additional Handling charge that should have been billed instead.
      recoverable: round2((amounts.oversize[tier] - amounts.ahsDimension[tier]) * (1 + FUEL_PCT)),
      note: `Longest side 60 in, length plus girth 128 in, 17,280 cubic in. Oversize needs more than 96, 130, or 17,280. Additional Handling, Dimension, applies instead at $${amounts.ahsDimension[tier].toFixed(2)}, so the recovery is the difference.`,
    });
  }

  // 8. Fuel computed at the wrong percentage on one package.
  {
    const p = at(31);
    const fixed = correctCharges(p, FUEL_PCT);
    p.charges = fixed.charges;
    p.billedLb = fixed.billedLb;
    const expected = fixed.charges.find((c) => c.code === "FUEL")!.amount;
    const wrong = round2(expected * (0.185 / FUEL_PCT));
    setCharge(p.charges, "FUEL", wrong);
    planted.push({
      kind: "FUEL_WRONG_PERCENT",
      tracking: p.tracking,
      code: "FUEL",
      ruleId: "FUEL",
      billed: wrong,
      expected,
      recoverable: round2(wrong - expected),
      note: "Fuel on this line works out to 18.5% of the base. The invoice period states 16.5%.",
    });
  }

  const total = round2(
    packages.reduce((sum, p) => sum + p.charges.reduce((s, c) => s + c.amount, 0), 0),
  );

  return {
    invoice: {
      number: `FX-${String(seed).slice(-6)}-01`,
      carrier: "FedEx",
      periodStart: PERIOD_START,
      periodEnd: PERIOD_END,
      fuelPct: FUEL_PCT,
      originZip3: ORIGIN_ZIP3,
      originLabel: ORIGIN_LABEL,
      packages,
      total,
    },
    planted,
  };
}

export function packageTotal(p: InvoicePackage): number {
  return round2(p.charges.reduce((s, c) => s + c.amount, 0));
}

export const invoiceProvenance = {
  kind: "Synthetic invoice generated by a seeded formula in this repository.",
  detail:
    "Forty FedEx Ground and Home Delivery packages from one origin, destinations drawn from public Census ZIP3 geography, zones from ZIP3 distance bands, transportation charges from the site's synthetic rate table at roughly half of list, and surcharge amounts at the published 2026 FedEx figures.",
  errors:
    "Eight billing errors are planted on fixed positions: the answer key the audit is scored against. They are the kinds of error parcel auditors find every week, at amounts a real invoice would carry.",
  notRepresenting: "Not a real invoice, not a real shipper, and nothing from an employer or a merchant.",
} as const;
