/**
 * Synthetic order profile for the dim weight lab.
 *
 * Every item here is generated by a seeded formula. The categories are shaped
 * like a general direct to consumer catalog: light soft goods, small fragile
 * goods, dense goods, and bulky goods that weigh almost nothing. That spread is
 * the point, because dimensional weight hits one end of it and ignores the
 * other. Destinations and the residential flag come from the same synthetic
 * order book the zone optimizer uses, shipped from one central node.
 */
import { getZone, type Zone } from "@/lib/zones";
import {
  DEFAULT_SEED,
  generateOrders,
  mulberry32,
} from "@/lib/labs/zone-optimizer/orders";
import type { Dims } from "./billing";

export type CategoryId = "apparel" | "beauty" | "home" | "bedding" | "dense";

export type Category = {
  id: CategoryId;
  label: string;
  share: number;
  length: [number, number];
  width: [number, number];
  height: [number, number];
  weightLb: [number, number];
  /** Soft, non fragile, and allowed to ship in a poly mailer. */
  mailerEligible: boolean;
  /** Height kept when a soft item is bagged rather than boxed. */
  bagCompression: number;
};

export const categories: Category[] = [
  {
    id: "apparel",
    label: "Apparel",
    share: 0.32,
    length: [9, 14],
    width: [7, 11],
    height: [1, 4],
    weightLb: [0.3, 2],
    mailerEligible: true,
    bagCompression: 0.8,
  },
  {
    id: "beauty",
    label: "Beauty and small goods",
    share: 0.22,
    length: [3, 7],
    width: [2, 5],
    height: [1.5, 4],
    weightLb: [0.2, 1.5],
    mailerEligible: false,
    bagCompression: 1,
  },
  {
    id: "home",
    label: "Home goods",
    share: 0.2,
    length: [8, 16],
    width: [6, 12],
    height: [4, 10],
    weightLb: [3, 12],
    mailerEligible: false,
    bagCompression: 1,
  },
  {
    id: "bedding",
    label: "Bedding and pillows",
    share: 0.12,
    length: [14, 20],
    width: [12, 16],
    height: [5, 9],
    weightLb: [1.5, 5],
    mailerEligible: true,
    bagCompression: 0.6,
  },
  {
    id: "dense",
    label: "Dense goods",
    share: 0.14,
    length: [4, 9],
    width: [3, 7],
    height: [3, 6],
    weightLb: [3, 12],
    mailerEligible: false,
    bagCompression: 1,
  },
];

export const categoriesById = new Map(categories.map((c) => [c.id, c]));

/** Central origin, so the zone mix is neither coastal best case nor worst. */
export const ORIGIN_ZIP3 = "660";
export const ORIGIN_LABEL = "Kansas City, KS";

export const DEFAULT_ITEM_COUNT = 20000;

export type SyntheticItem = {
  category: CategoryId;
  dims: Dims;
  weightLb: number;
  zone: Zone;
  residential: boolean;
};

function between(random: () => number, [low, high]: [number, number]): number {
  return low + random() * (high - low);
}

const quarterInch = (value: number) => Math.round(value * 4) / 4;
const tenthPound = (value: number) => Math.round(value * 10) / 10;

const cache = new Map<string, SyntheticItem[]>();

export function generateItems(
  count: number = DEFAULT_ITEM_COUNT,
  seed: number = DEFAULT_SEED,
): SyntheticItem[] {
  const key = `${count}:${seed}`;
  const cached = cache.get(key);
  if (cached) return cached;

  const destinations = generateOrders(count, seed);
  const random = mulberry32(seed + 1);
  const items: SyntheticItem[] = [];

  for (const order of destinations) {
    const zone = getZone(ORIGIN_ZIP3, order.destZip3);
    if (zone === undefined) continue;

    const draw = random();
    let cumulative = 0;
    let category = categories[categories.length - 1];
    for (const candidate of categories) {
      cumulative += candidate.share;
      if (draw < cumulative) {
        category = candidate;
        break;
      }
    }

    const sides = [
      quarterInch(between(random, category.length)),
      quarterInch(between(random, category.width)),
      quarterInch(between(random, category.height)),
    ].sort((a, b) => b - a);

    items.push({
      category: category.id,
      dims: { length: sides[0], width: sides[1], height: sides[2] },
      weightLb: tenthPound(between(random, category.weightLb)),
      zone,
      residential: order.residential,
    });
  }

  cache.set(key, items);
  return items;
}

export const itemDataProvenance = {
  kind: "Synthetic. Generated by seeded formula, not sampled from any real catalog or order file.",
  items:
    "Five categories with stated share, size range, and weight range, drawn uniformly inside each range and rounded to the quarter inch and tenth of a pound.",
  destinations: `Destinations and the residential flag reuse the zone optimizer's synthetic order book, shipped from ${ORIGIN_LABEL} so the zone mix sits mid range.`,
  seed: DEFAULT_SEED,
};
