/**
 * Synthetic order dataset.
 *
 * Nothing here comes from a real order file. Destinations are drawn from a
 * demand proxy built out of public ZCTA geography, weights are drawn from a
 * lognormal shaped distribution typical of direct to consumer parcel, and the
 * generator is seeded, so every run produces the identical dataset and any
 * number shown in the lab can be reproduced.
 */
import { getCentroid, listZip3, type Zip3Centroid } from "@/lib/zones";

export type SyntheticOrder = {
  destZip3: string;
  weightLb: number;
  residential: boolean;
};

/** Deterministic PRNG. Same seed, same dataset, every time. */
export function mulberry32(seed: number): () => number {
  let a = seed;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/**
 * Demand weight per ZIP3.
 *
 * Two public signals, no order data. The count of ZCTAs in a ZIP3 tracks how
 * many postal delivery areas it contains, which is a rough stand in for people.
 * ZCTAs per square mile tracks density, and ecommerce demand skews urban, so
 * density gets a sublinear boost rather than a linear one.
 */
function demandWeight(centroid: Zip3Centroid, medianDensity: number): number {
  const density = centroid.zctaCount / Math.max(centroid.landSqMi, 1);
  const urbanBoost = Math.min(4, (density / medianDensity) ** 0.4);
  return centroid.zctaCount * urbanBoost;
}

function median(values: number[]): number {
  const sorted = [...values].sort((a, b) => a - b);
  const middle = Math.floor(sorted.length / 2);
  return sorted.length % 2 === 0
    ? (sorted[middle - 1] + sorted[middle]) / 2
    : sorted[middle];
}

export type DemandRow = { zip3: string; weight: number; share: number };

let cachedDemand: DemandRow[] | undefined;

export function getDemandDistribution(): DemandRow[] {
  if (cachedDemand) return cachedDemand;

  const centroids = listZip3()
    .map((zip3) => getCentroid(zip3))
    .filter((centroid): centroid is Zip3Centroid => Boolean(centroid));

  const medianDensity = median(
    centroids.map((c) => c.zctaCount / Math.max(c.landSqMi, 1)),
  );

  const weights = centroids.map((centroid) => ({
    zip3: centroid.zip3,
    weight: demandWeight(centroid, medianDensity),
  }));

  const total = weights.reduce((sum, row) => sum + row.weight, 0);
  cachedDemand = weights.map((row) => ({
    ...row,
    share: row.weight / total,
  }));
  return cachedDemand;
}

/**
 * Package weight in pounds, lognormal shaped and clipped to the rate table.
 * Median lands near three pounds, with a tail into the twenties, which is the
 * shape most direct to consumer parcel profiles take.
 */
function drawWeightLb(random: () => number): number {
  const u1 = Math.max(random(), 1e-9);
  const u2 = random();
  const standardNormal =
    Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2);
  const weight = Math.exp(1.05 + 0.75 * standardNormal);
  return Math.min(70, Math.max(1, Math.round(weight * 10) / 10));
}

export const DEFAULT_ORDER_COUNT = 20000;
export const DEFAULT_SEED = 20260912;

/** Share of orders delivering to a residential address. */
export const RESIDENTIAL_SHARE = 0.87;

const cache = new Map<string, SyntheticOrder[]>();

export function generateOrders(
  count: number = DEFAULT_ORDER_COUNT,
  seed: number = DEFAULT_SEED,
): SyntheticOrder[] {
  const key = `${count}:${seed}`;
  const cached = cache.get(key);
  if (cached) return cached;

  const demand = getDemandDistribution();
  const cumulative: number[] = [];
  let running = 0;
  for (const row of demand) {
    running += row.share;
    cumulative.push(running);
  }

  const random = mulberry32(seed);
  const orders: SyntheticOrder[] = new Array(count);

  for (let i = 0; i < count; i += 1) {
    const draw = random();
    let low = 0;
    let high = cumulative.length - 1;
    while (low < high) {
      const mid = (low + high) >> 1;
      if (cumulative[mid] < draw) low = mid + 1;
      else high = mid;
    }
    orders[i] = {
      destZip3: demand[low].zip3,
      weightLb: drawWeightLb(random),
      residential: random() < RESIDENTIAL_SHARE,
    };
  }

  cache.set(key, orders);
  return orders;
}

export const orderDataProvenance = {
  kind: "Synthetic. Generated by seeded formula, not sampled from any real order file.",
  destinations:
    "Drawn from a demand proxy built on public US Census ZCTA counts and land area per ZIP3. Denser prefixes receive a sublinear boost because ecommerce demand skews urban.",
  weights:
    "Lognormal shaped, median near three pounds, clipped to the one to seventy pound rate table.",
  residentialShare: RESIDENTIAL_SHARE,
  seed: DEFAULT_SEED,
  reproducible:
    "Same seed, same dataset, every run. Every figure in the lab can be reproduced from this file.",
};
