/**
 * Build lib/rates/synthetic-ground-rates.json.
 *
 * Every number in the output is synthetic. The grid is shaped like a published
 * ground list rate table, meaning it rises with weight and rises faster in the
 * far zones, because that is the structure the lab needs in order to be
 * instructive. The level is set to roughly half of list, which is where a
 * mid-volume ecommerce shipper tends to land after discounts, so a reader who
 * knows parcel sees plausible dollars instead of retail ones. It is not any
 * carrier's rate table and it is not a negotiated agreement.
 *
 * Usage: pnpm rates:generate
 */
import fs from "node:fs";
import path from "node:path";
import { ZONES } from "../lib/zones/bands";

const MAX_WEIGHT_LB = 70;

/**
 * Synthetic shape: a zone dependent floor plus a weight term that steepens by
 * zone. Every coefficient is half of the original list shaped table, so the
 * ratios between cells, and every percentage the labs report, are unchanged.
 */
function syntheticRate(zone: number, weightLb: number): number {
  const zoneStep = zone - 2;
  const floor = 4.0 + 0.31 * zoneStep ** 1.25;
  const perWeight = 0.275 + 0.0425 * zoneStep;
  return Number((floor + weightLb ** 0.92 * perWeight).toFixed(2));
}

const rates: Record<string, Record<string, number>> = {};
for (const zone of ZONES) {
  const column: Record<string, number> = {};
  for (let weight = 1; weight <= MAX_WEIGHT_LB; weight += 1) {
    column[String(weight)] = syntheticRate(zone, weight);
  }
  rates[String(zone)] = column;
}

const output = {
  _provenance: {
    kind: "Synthetic. Every figure was generated by formula.",
    formula:
      "rate = 4.00 + 0.31 * (zone - 2)^1.25 + weightLb^0.92 * (0.275 + 0.0425 * (zone - 2))",
    intent:
      "Reproduce the shape of a published ground list rate table, rising with weight and rising faster in the far zones, at roughly half of list, which is the range a mid-volume ecommerce shipper tends to pay after discounts.",
    notRepresenting:
      "No carrier rate card, no negotiated agreement, no employer pricing. Replace this file to plug in published list rates with their own provenance.",
    surcharges:
      "Fuel is a percentage of the base rate. Residential is a flat add. Both are synthetic and stated in lib/rates/index.ts.",
    weightBreaks: `1 to ${MAX_WEIGHT_LB} pounds, one pound increments`,
    generatedBy: "scripts/generate-rate-table.ts",
    generatedOn: new Date().toISOString().slice(0, 10),
  },
  rates,
};

const target = path.join(
  process.cwd(),
  "lib",
  "rates",
  "synthetic-ground-rates.json",
);
fs.writeFileSync(target, `${JSON.stringify(output)}\n`);
console.log(`Wrote ${ZONES.length} zones by ${MAX_WEIGHT_LB} weight breaks.`);
