/**
 * Build lib/rates/synthetic-ground-rates.json.
 *
 * Every number in the output is synthetic. The grid is shaped like a published
 * ground list rate table, meaning it rises with weight and rises faster in the
 * far zones, because that is the structure the lab needs in order to be
 * instructive. It is not any carrier's rate table and it is not a negotiated
 * agreement.
 *
 * Usage: pnpm rates:generate
 */
import fs from "node:fs";
import path from "node:path";
import { ZONES } from "../lib/zones/bands";

const MAX_WEIGHT_LB = 70;

/** Synthetic shape: a zone dependent floor plus a weight term that steepens by zone. */
function syntheticRate(zone: number, weightLb: number): number {
  const zoneStep = zone - 2;
  const floor = 8.0 + 0.62 * zoneStep ** 1.25;
  const perWeight = 0.55 + 0.085 * zoneStep;
  return Number((floor + weightLb ** 0.92 * perWeight).toFixed(2));
}

const rates: Record<string, Record<string, number>> = {};
for (const zone of ZONES) {
  const column: Record<string, number> = {};
  for (let weight = 1; weight <= MAX_WEIGHT_LB; weight += 1) {
    column[String(weight)] = syntheticRate(zone, weight);
  }
  rates[String(zone)] = column;
}

const output = {
  _provenance: {
    kind: "Synthetic. Every figure was generated by formula.",
    formula:
      "rate = 8.00 + 0.62 * (zone - 2)^1.25 + weightLb^0.92 * (0.55 + 0.085 * (zone - 2))",
    intent:
      "Reproduce the shape of a published ground list rate table: rising with weight, rising faster in the far zones.",
    notRepresenting:
      "No carrier rate card, no negotiated agreement, no employer pricing. Replace this file to plug in published list rates with their own provenance.",
    surcharges:
      "Fuel is a percentage of the base rate. Residential is a flat add. Both are synthetic and stated in lib/rates/index.ts.",
    weightBreaks: `1 to ${MAX_WEIGHT_LB} pounds, one pound increments`,
    generatedBy: "scripts/generate-rate-table.ts",
    generatedOn: new Date().toISOString().slice(0, 10),
  },
  rates,
};

const target = path.join(
  process.cwd(),
  "lib",
  "rates",
  "synthetic-ground-rates.json",
);
fs.writeFileSync(target, `${JSON.stringify(output)}\n`);
console.log(`Wrote ${ZONES.length} zones by ${MAX_WEIGHT_LB} weight breaks.`);
